using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace Core.HtmlElements
{
   public  enum Bootstarp图标样式类型
    {
        [Description("glyphicon-asterisk")]
        glyphicon_asterisk,
        [Description("glyphicon-plus")]
        glyphicon_plus,
        [Description("glyphicon-euro")]
        glyphicon_euro,
        [Description("glyphicon-minus")]
        glyphicon_minus,
        [Description("glyphicon-cloud")]
        glyphicon_cloud,
        [Description("glyphicon-envelope")]
        glyphicon_envelope,
        [Description("glyphicon-pencil")]
        glyphicon_pencil,
        [Description("glyphicon-glass")]
        glyphicon_glass,
        [Description("glyphicon-music")]
        glyphicon_music,
        [Description("glyphicon-search")]
        glyphicon_search,
        [Description("glyphicon-heart")]
        glyphicon_heart,
        [Description("glyphicon-star")]
        glyphicon_star,
        [Description("glyphicon-star-empty")]
        glyphicon_star_empty,
        [Description("glyphicon-user")]
        glyphicon_user,
        [Description("glyphicon-film")]
        glyphicon_film,
        [Description("glyphicon-th-large")]
        glyphicon_th_large,
        [Description("glyphicon-th")]
        glyphicon_th,
        [Description("glyphicon-th-list")]
        glyphicon_th_list,
        [Description("glyphicon-ok")]
        glyphicon_ok,
        [Description("glyphicon-remove")]
        glyphicon_remove,
        [Description("glyphicon-zoom-in")]
        glyphicon_zoom_in,
        [Description("glyphicon-zoom-out")]
        glyphicon_zoom_out,
        [Description("glyphicon-off")]
        glyphicon_off,
        [Description("glyphicon-signal")]
        glyphicon_signal,
        [Description("glyphicon-cog")]
        glyphicon_cog,
        [Description("glyphicon-trash")]
        glyphicon_trash,
        [Description("glyphicon-home")]
        glyphicon_home,
        [Description("glyphicon-file")]
        glyphicon_file,
        [Description("glyphicon-time")]
        glyphicon_time,
        [Description("glyphicon-road")]
        glyphicon_road,
        [Description("glyphicon-download-alt")]
        glyphicon_download_alt,
        [Description("glyphicon-download")]
        glyphicon_download,
        [Description("glyphicon-upload")]
        glyphicon_upload,
        [Description("glyphicon-inbox")]
        glyphicon_inbox,
        [Description("glyphicon-play-circle")]
        glyphicon_play_circle,
        [Description("glyphicon-repeat")]
        glyphicon_repeat,
        [Description("glyphicon-refresh")]
        glyphicon_refresh,
        [Description("glyphicon-list-alt")]
        glyphicon_list_alt,
        [Description("glyphicon-lock")]
        glyphicon_lock,
        [Description("glyphicon-flag")]
        glyphicon_flag,
        [Description("glyphicon-headphones")]
        glyphicon_headphones,
        [Description("glyphicon-volume-off")]
        glyphicon_volume_off,
        [Description("glyphicon-volume-down")]
        glyphicon_volume_down,
        [Description("glyphicon-volume-up")]
        glyphicon_volume_up,
        [Description("glyphicon-qrcode")]
        glyphicon_qrcode,
        [Description("glyphicon-barcode")]
        glyphicon_barcode,
        [Description("glyphicon-tag")]
        glyphicon_tag,
        [Description("glyphicon-tags")]
        glyphicon_tags,
        [Description("glyphicon-book")]
        glyphicon_book,
        [Description("glyphicon-bookmark")]
        glyphicon_bookmark,
        [Description("glyphicon-print")]
        glyphicon_print,
        [Description("glyphicon-camera")]
        glyphicon_camera,
        [Description("glyphicon-font")]
        glyphicon_font,
        [Description("glyphicon-bold")]
        glyphicon_bold,
        [Description("glyphicon-italic")]
        glyphicon_italic,
        [Description("glyphicon-text-height")]
        glyphicon_text_height,
        [Description("glyphicon-text-width")]
        glyphicon_text_width,
        [Description("glyphicon-align-left")]
        glyphicon_align_left,
        [Description("glyphicon-align-center")]
        glyphicon_align_center,
        [Description("glyphicon-align-right")]
        glyphicon_align_right,
        [Description("glyphicon-align-justify")]
        glyphicon_align_justify,
        [Description("glyphicon-list")]
        glyphicon_list,
        [Description("glyphicon-indent-left")]
        glyphicon_indent_left,
        [Description("glyphicon-indent-right")]
        glyphicon_indent_right,
        [Description("glyphicon-facetime-video")]
        glyphicon_facetime_video,
        [Description("glyphicon-picture")]
        glyphicon_picture,
        [Description("glyphicon-map-marker")]
        glyphicon_map_marker,
        [Description("glyphicon-adjust")]
        glyphicon_adjust,
        [Description("glyphicon-tint")]
        glyphicon_tint,
        [Description("glyphicon-edit")]
        glyphicon_edit,
        [Description("glyphicon-share")]
        glyphicon_share,
        [Description("glyphicon-check")]
        glyphicon_check,
        [Description("glyphicon-move")]
        glyphicon_move,
        [Description("glyphicon-step-backward")]
        glyphicon_step_backward,
        [Description("glyphicon-fast-backward")]
        glyphicon_fast_backward,
        [Description("glyphicon-backward")]
        glyphicon_backward,
        [Description("glyphicon-play")]
        glyphicon_play,
        [Description("glyphicon-pause")]
        glyphicon_pause,
        [Description("glyphicon-stop")]
        glyphicon_stop,
        [Description("glyphicon-forward")]
        glyphicon_forward,
        [Description("glyphicon-fast-forward")]
        glyphicon_fast_forward,
        [Description("glyphicon-step-forward")]
        glyphicon_step_forward,
        [Description("glyphicon-eject")]
        glyphicon_eject,
        [Description("glyphicon-chevron-left")]
        glyphicon_chevron_left,
        [Description("glyphicon-chevron-right")]
        glyphicon_chevron_right,
        [Description("glyphicon-plus-sign")]
        glyphicon_plus_sign,
        [Description("glyphicon-minus-sign")]
        glyphicon_minus_sign,
        [Description("glyphicon-remove-sign")]
        glyphicon_remove_sign,
        [Description("glyphicon-ok-sign")]
        glyphicon_ok_sign,
        [Description("glyphicon-question-sign")]
        glyphicon_question_sign,
        [Description("glyphicon-info-sign")]
        glyphicon_info_sign,
        [Description("glyphicon-screenshot")]
        glyphicon_screenshot,
        [Description("glyphicon-remove-circle")]
        glyphicon_remove_circle,
        [Description("glyphicon-ok-circle")]
        glyphicon_ok_circle,
        [Description("glyphicon-ban-circle")]
        glyphicon_ban_circle,
        [Description("glyphicon-arrow-left")]
        glyphicon_arrow_left,
        [Description("glyphicon-arrow-right")]
        glyphicon_arrow_right,
        [Description("glyphicon-arrow-up")]
        glyphicon_arrow_up,
        [Description("glyphicon-arrow-down")]
        glyphicon_arrow_down,
        [Description("glyphicon-share-alt")]
        glyphicon_share_alt,
        [Description("glyphicon-resize-full")]
        glyphicon_resize_full,
        [Description("glyphicon-resize-small")]
        glyphicon_resize_small,
        [Description("glyphicon-exclamation-sign")]
        glyphicon_exclamation_sign,
        [Description("glyphicon-gift")]
        glyphicon_gift,
        [Description("glyphicon-leaf")]
        glyphicon_leaf,
        [Description("glyphicon-fire")]
        glyphicon_fire,
        [Description("glyphicon-eye-open")]
        glyphicon_eye_open,
        [Description("glyphicon-eye-close")]
        glyphicon_eye_close,
        [Description("glyphicon-warning-sign")]
        glyphicon_warning_sign,
        [Description("glyphicon-plane")]
        glyphicon_plane,
        [Description("glyphicon-calendar")]
        glyphicon_calendar,
        [Description("glyphicon-random")]
        glyphicon_random,
        [Description("glyphicon-comment")]
        glyphicon_comment,
        [Description("glyphicon-magnet")]
        glyphicon_magnet,
        [Description("glyphicon-chevron-up")]
        glyphicon_chevron_up,
        [Description("glyphicon-chevron-down")]
        glyphicon_chevron_down,
        [Description("glyphicon-retweet")]
        glyphicon_retweet,
        [Description("glyphicon-shopping-cart")]
        glyphicon_shopping_cart,
        [Description("glyphicon-folder-close")]
        glyphicon_folder_close,
        [Description("glyphicon-folder-open")]
        glyphicon_folder_open,
        [Description("glyphicon-resize-vertical")]
        glyphicon_resize_vertical,
        [Description("glyphicon-resize-horizontal")]
        glyphicon_resize_horizontal,
        [Description("glyphicon-hdd")]
        glyphicon_hdd,
        [Description("glyphicon-bullhorn")]
        glyphicon_bullhorn,
        [Description("glyphicon-bell")]
        glyphicon_bell,
        [Description("glyphicon-certificate")]
        glyphicon_certificate,
        [Description("glyphicon-thumbs-up")]
        glyphicon_thumbs_up,
        [Description("glyphicon-thumbs-down")]
        glyphicon_thumbs_down,
        [Description("glyphicon-hand-right")]
        glyphicon_hand_right,
        [Description("glyphicon-hand-left")]
        glyphicon_hand_left,
        [Description("glyphicon-hand-up")]
        glyphicon_hand_up,
        [Description("glyphicon-hand-down")]
        glyphicon_hand_down,
        [Description("glyphicon-circle-arrow-right")]
        glyphicon_circle_arrow_right,
        [Description("glyphicon-circle-arrow-left")]
        glyphicon_circle_arrow_left,
        [Description("glyphicon-circle-arrow-up")]
        glyphicon_circle_arrow_up,
        [Description("glyphicon-circle-arrow-down")]
        glyphicon_circle_arrow_down,
        [Description("glyphicon-globe")]
        glyphicon_globe,
        [Description("glyphicon-wrench")]
        glyphicon_wrench,
        [Description("glyphicon-tasks")]
        glyphicon_tasks,
        [Description("glyphicon-filter")]
        glyphicon_filter,
        [Description("glyphicon-briefcase")]
        glyphicon_briefcase,
        [Description("glyphicon-fullscreen")]
        glyphicon_fullscreen,
        [Description("glyphicon-dashboard")]
        glyphicon_dashboard,
        [Description("glyphicon-paperclip")]
        glyphicon_paperclip,
        [Description("glyphicon-heart-empty")]
        glyphicon_heart_empty,
        [Description("glyphicon-link")]
        glyphicon_link,
        [Description("glyphicon-phone")]
        glyphicon_phone,
        [Description("glyphicon-pushpin")]
        glyphicon_pushpin,
        [Description("glyphicon-usd")]
        glyphicon_usd,
        [Description("glyphicon-gbp")]
        glyphicon_gbp,
        [Description("glyphicon-sort")]
        glyphicon_sort,
        [Description("glyphicon-sort-by-alphabet")]
        glyphicon_sort_by_alphabet,
        [Description("glyphicon-sort-by-alphabet-alt")]
        glyphicon_sort_by_alphabet_alt,
        [Description("glyphicon-sort-by-order")]
        glyphicon_sort_by_order,
        [Description("glyphicon-sort-by-order-alt")]
        glyphicon_sort_by_order_alt,
        [Description("glyphicon-sort-by-attributes")]
        glyphicon_sort_by_attributes,
        [Description("glyphicon-sort-by-attributes-alt")]
        glyphicon_sort_by_attributes_alt,
        [Description("glyphicon-unchecked")]
        glyphicon_unchecked,
        [Description("glyphicon-expand")]
        glyphicon_expand,
        [Description("glyphicon-collapse-down")]
        glyphicon_collapse_down,
        [Description("glyphicon-collapse-up")]
        glyphicon_collapse_up,
        [Description("glyphicon-log-in")]
        glyphicon_log_in,
        [Description("glyphicon-flash")]
        glyphicon_flash,
        [Description("glyphicon-log-out")]
        glyphicon_log_out,
        [Description("glyphicon-new-window")]
        glyphicon_new_window,
        [Description("glyphicon-record")]
        glyphicon_record,
        [Description("glyphicon-save")]
        glyphicon_save,
        [Description("glyphicon-open")]
        glyphicon_open,
        [Description("glyphicon-saved")]
        glyphicon_saved,
        [Description("glyphicon-import")]
        glyphicon_import,
        [Description("glyphicon-export")]
        glyphicon_export,
        [Description("glyphicon-send")]
        glyphicon_send,
        [Description("glyphicon-floppy-disk")]
        glyphicon_floppy_disk,
        [Description("glyphicon-floppy-saved")]
        glyphicon_floppy_saved,
        [Description("glyphicon-floppy-remove")]
        glyphicon_floppy_remove,
        [Description("glyphicon-floppy-save")]
        glyphicon_floppy_save,
        [Description("glyphicon-floppy-open")]
        glyphicon_floppy_open,
        [Description("glyphicon-credit-card")]
        glyphicon_credit_card,
        [Description("glyphicon-transfer")]
        glyphicon_transfer,
        [Description("glyphicon-cutlery")]
        glyphicon_cutlery,
        [Description("glyphicon-header")]
        glyphicon_header,
        [Description("glyphicon-compressed")]
        glyphicon_compressed,
        [Description("glyphicon-earphone")]
        glyphicon_earphone,
        [Description("glyphicon-phone-alt")]
        glyphicon_phone_alt,
        [Description("glyphicon-tower")]
        glyphicon_tower,
        [Description("glyphicon-stats")]
        glyphicon_stats,
        [Description("glyphicon-sd-video")]
        glyphicon_sd_video,
        [Description("glyphicon-hd-video")]
        glyphicon_hd_video,
        [Description("glyphicon-subtitles")]
        glyphicon_subtitles,
        [Description("glyphicon-sound-stereo")]
        glyphicon_sound_stereo,
        [Description("glyphicon-sound-dolby")]
        glyphicon_sound_dolby,
        [Description("glyphicon-sound-5-1")]
        glyphicon_sound_5_1,
        [Description("glyphicon-sound-6-1")]
        glyphicon_sound_6_1,
        [Description("glyphicon-sound-7-1")]
        glyphicon_sound_7_1,
        [Description("glyphicon-copyright-mark")]
        glyphicon_copyright_mark,
        [Description("glyphicon-registration-mark")]
        glyphicon_registration_mark,
        [Description("glyphicon-cloud-download")]
        glyphicon_cloud_download,
        [Description("glyphicon-cloud-upload")]
        glyphicon_cloud_upload,
        [Description("glyphicon-tree-conifer")]
        glyphicon_tree_conifer,
        [Description("glyphicon-tree-deciduous")]
        glyphicon_tree_deciduous
    }
}
